language: cpp

env:
  global:
   - secure: "uaR7xzMIqCCFVGuOSN/YmcLmtUVPj5x26+yy2PA6xZ+XTS8I2HUanNCXOD4w3VQHsOZld6kcmSb/nNNNPrKbamGc+fumatsEh9lLE7Y4gRr/1mFeyKg7j4cOFLdiK+PVCAA0KuAxJ15PhOF4y5PdCLTXDgoC6nYpftAe9Zh+w494EMZSeewkM2xATPZRy54Wb6ONknciRy60AwUguM43lGOaKT55ACQM6VQtBXWWrdHexTeiEB7xZ4DHMn1BIFDLqzGs+rx4m/Al5C/wIR7ccu0hQH+0oWTmP/1WZdhpiLYB42+Atlgm4+T9OYKtkYZ96yMQ36LVOEYy5GM23K1TuBfdSuLGxOE+G+MgCxBkbZ+Ui0cs4m2f4nnSH6g18bPHkQIgoWD3eFJgCUkDFmmApDn7iOGm2sfgxl+y/+DyqZd4UuydoEchZXV6r1CRL9TIcptjx8aSrr3vKQYxuf8VUum3AzJEBQUMBzmisJt6VUd7i+EtnYH62yZ2CCO3x/J7lX54Y9TBU+ZC4+0Y0R+jhr0vcSJ1ADuT8L6kRwqkFvtAgdO7yOoSwPA7dHTgxcrdeJJM9FGPnzAZ0Iw+6myPEIK68tWR7DdeB5612wEDnQ4tEzbUo19dhWOD1LLPkcTkX9yeYOOrcjH9/zi4H5ZHCqIq/zMzLXDyd6GhBxb2rjI="

matrix:
  include:
  - os: osx
    compiler: clang

    script:
      - xcodebuild -configuration Debug
      - xcodebuild -configuration Release
      - xcodebuild analyze -quiet -configuration Debug CLANG_ANALYZER_OUTPUT=plist-html CLANG_ANALYZER_OUTPUT_DIR="$(pwd)/clang-analyze" && [ "$(find clang-analyze -name "*.html")" = "" ]
      - xcodebuild analyze -quiet -configuration Release CLANG_ANALYZER_OUTPUT=plist-html CLANG_ANALYZER_OUTPUT_DIR="$(pwd)/clang-analyze" && [ "$(find clang-analyze -name "*.html")" = "" ]

    deploy:
      provider: releases
      skip_cleanup: true
      file: "build/*/*.zip"
      file_glob: true
      api_key:
        secure: Veb9Vu1sHfbnUCLYszLaH5TOL98YgXF+JDH/+uQ2ecyFurXiS7Ka05+/OOEx7En73d1262BvCGeLgelz4cVbR4z5p4S5sVnusiTZm0aAAL1tvAQgA/HtFnYHwn4yKaqI10BOm8HqxTWjyH+Fk4/Q6gOBHOGfIUOcMKGpFbS2IJByVaQIIlL/FIYH4HbV3a2IN+gXPpmbtMfGv4kwtoL816TmPRb5fWxcgIqOyyMOEUgcqgQ5i2J/2JMYRjsFdDXo4k2yb2vv0Nh4zV/UNF9DgMBZGFO0uZIDwxeHU0w5vrEMEopGTThVNQ9X0Ya+ofkzHehR0aPZYIsbHnAiFdmlUX8JLGyifMGnlG8HLppYBOfqxdz8gSwDyn/tGg8gzVYoyl3EpZEzyo/+ZEt2+2qV+YwUhGoyFj/e9g04SMeql8xil+d1qlOMV8d0EZeKXHtCCNFrGlO9pVl+/6xTX0bm3Nss+i1eYqsldOCDJp1KmwRInKeSG2/EBy+ZWpS8O7FGEAqVRRcH1caAchZAazDotOWjBucIn7z1dWTVD8wJztJGER9SFDxniib7Xyz56j2Wbb+Aozf0E5nglgkdUyalYxvupwUQhlkzdHdUr0EM39DevyR4H80GN0EPHoJovZbLMrVIsXVASl61FMxwYD9IDhbnhUh4NMJJD07c3EDih5I=
      on:
        tags: true

  - os: osx
    osx_image: xcode6.4
    compiler: clang

    script:
      - echo "This script runs coverity..."

    addons:
      coverity_scan:
        project:
          name: "acidanthera/MaciASL"
          description: "MaciASL"
        notification_email: $NOTIFICATION_EMAIL
        build_command: "xcodebuild -configuration Release"
        branch_pattern: master
